### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by emilepharand** [emilepharand/Babilonia#26]
- [x] Research how GitHub Actions works
- [x] Set up a pipeline that
  - [x] Checks build
  - [x] Scans for code quality #157 
    - [x] Static analysis and duplications #173
    - [x] Linter #172 
    - [x] Security
  - [x] Runs all tests
  - [x] Collects test coverage (codecov) #164 
  
https://github.com/marketplace?category=&query=&type=actions
